POST http://localhost:3333/events
Content-Type: application/json

{
  "title": "Título de Teste",
  "details": "Esse evento é só para um participante 😂",
  "maximum_attendees": 1
}

###

POST http://localhost:3333/events/clv21xmnd000014ijykhwdyvp/attendees
Content-Type: application/json

{
  "name": "Bruce Wayne",
  "email": "bruce@email.com"
}

###
GET http://localhost:3333/events/clv21xmnd000014ijykhwdyvp

###
GET http://localhost:3333/attendees/5/badge


###
GET http://localhost:3333/attendees/5/check-in


###
GET http://localhost:3333/events/clv21xmnd000014ijykhwdyvp/attendees

###
GET http://localhost:3333/events/clv21xmnd000014ijykhwdyvp/attendees?query=bruce
